title:            Tw93
description:      Describe your website here.

# put your disqus here
disqus_shortname: tw93
reading_time:     false # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:              # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://tw93.github.io

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Categories'
    url: '/categories'
  - title: 'About'
    url: '/about'


# Owner/author information
owner:
  name:           Tw93
  site:           http://tw93.github.io
  avatar:         images/config/me.jpg
  bio:            "Keep calm and learn javascript."
  email:          tangweiyuanyou@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter:  # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: tw93

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/tw93"
  - title: "weibo"
    url: "http://weibo.com/2218703493/profile?topnav=1&wvr=6"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
locale:      zh_CN
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year-:month-:day/:title.html

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: false

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
